'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ResumenEstimaciones
    
    '''<summary>
    '''div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ButtonIndicadores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonIndicadores As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonPrintEstim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonPrintEstim As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ButtonEstimacionGo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonEstimacionGo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlContents3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlContents3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tableQuotations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableQuotations As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DDUsers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDUsers As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BTN_ACEPTAR_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_ACEPTAR_1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''quotations_reasign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quotations_reasign As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    
    '''<summary>
    '''div_response control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_response As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
